# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testLogin(self):
    # Test name: TestLogin
    # Step # | name | target | value
    # 1 | open | /test/login.html | 
    self.driver.get("https://demo.guru99.com/test/login.html")
    # 2 | setWindowSize | 1160x879 | 
    self.driver.set_window_size(1160, 879)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | bebe1@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("bebe1@gmail.com")
    # 5 | click | id=passwd | 
    self.driver.find_element(By.ID, "passwd").click()
    # 6 | type | id=passwd | bb1
    self.driver.find_element(By.ID, "passwd").send_keys("bb1")
    # 7 | assertText | id=SubmitLogin | Sign in
    assert self.driver.find_element(By.ID, "SubmitLogin").text == "Sign in"
  
